@echo off
echo Deploying to S3...
aws s3 sync dist/ s3://enviro-centric-website-982534369227-us-west-1 --delete
echo Creating CloudFront invalidation...
aws cloudfront create-invalidation --distribution-id E1LT5NP0HIH0FO --paths "/*"
echo Deployment complete! 